name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install --frozen-lockfile
      
      - name: Update dependencies
        run: |
          # Update all dependencies to latest
          bun update
      
      - name: Run tests
        run: bun run test
        continue-on-error: true
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: '🔄 Weekly Dependency Updates'
          body: |
            ## Automated Dependency Updates
            
            This PR updates all dependencies to their latest versions.
            
            ### Changes
            - Updated all npm packages
            - Ran automated tests
            
            ### Checklist
            - [ ] Review changelog for breaking changes
            - [ ] Test locally if tests failed
            - [ ] Update documentation if needed
            
            ---
            *This PR was automatically created by the dependency update workflow*
          branch: deps/weekly-update
          delete-branch: true
          labels: dependencies, automated
