name: PR Quality Checks

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install dependencies
        working-directory: ./apps/site
        run: bun install --frozen-lockfile
      
      - name: Run linter
        working-directory: ./apps/site
        run: bun run lint

  typecheck:
    name: TypeScript Type Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install dependencies
        working-directory: ./apps/site
        run: bun install --frozen-lockfile
      
      - name: Run type check
        working-directory: ./apps/site
        run: bun run typecheck

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install dependencies
        working-directory: ./apps/site
        run: bun install --frozen-lockfile
      
      - name: Run tests
        working-directory: ./apps/site
        run: bun run test

  build:
    name: Build Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install dependencies
        working-directory: ./apps/site
        run: bun install --frozen-lockfile
      
      - name: Build site
        working-directory: ./apps/site
        run: bun run generate
        env:
          NUXT_PUBLIC_SITE_URL: https://openseadragon.github.io
      
      - name: Check bundle size
        working-directory: ./apps/site
        run: |
          if [ -d ".output/public" ]; then
            echo "Build successful!"
            du -sh .output/public
          else
            echo "Build failed - output directory not found"
            exit 1
          fi
